# https://github.com/actions/labeler
documentation:
    - changed-files:
        - any-glob-to-any-file:
            - "**/*.md"
            - docs/**
            - media/**
examples:
    - all:
        - changed-files:
            - any-glob-to-any-file:
                - app/**
                - examples/**
                - tools/**
            - all-globs-to-all-files:
                - '!tools/server/**'
                - '!tools/mtmd/**'
                - '!tools/ui/**'
testing:
    - changed-files:
        - any-glob-to-any-file:
            - tests/**
build:
    - changed-files:
        - any-glob-to-any-file:
            - cmake/**
            - CMakeLists.txt
            - CMakePresets.json
devops:
    - changed-files:
        - any-glob-to-any-file:
            - .devops/**
            - .github/**
            - ci/**
android:
    - changed-files:
        - any-glob-to-any-file:
            - examples/llama.android/**
server/ui:
    - changed-files:
        - any-glob-to-any-file:
            - tools/ui/**
server:
    - changed-files:
        - any-glob-to-any-file:
            - tools/server/**
mtmd:
    - changed-files:
        - any-glob-to-any-file:
            - tools/mtmd/**
conversion:
    - changed-files:
        - any-glob-to-any-file:
            - conversion/**
            - convert_*.py
            - gguf-py/**
vendor:
    - changed-files:
        - any-glob-to-any-file:
            - vendor/**
ggml:
    - changed-files:
        - any-glob-to-any-file:
            - ggml/**
model:
    - changed-files:
        - any-glob-to-any-file:
            - src/models/**
nix:
    - changed-files:
        - any-glob-to-any-file:
            - "**/*.nix"
            - .github/workflows/nix-*.yml
            - .devops/nix/nixpkgs-instances.nix
embedding:
    - changed-files:
        - any-glob-to-any-file: examples/embedding/
jinja parser:
    - changed-files:
        - any-glob-to-any-file:
            - common/jinja/**
