name: Models Backend Check

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
    paths: [
      '.github/workflows/models-check.yml',
      'ggml/**',
      'tests/fusion/**',
      'tests/test-fusion.cpp',
      'tests/test-llama-archs.cpp',
      'src/llama-graph.cpp',
      'src/llama-model*',
      'src/models/**'
    ]

  pull_request:
    types: [opened, synchronize, reopened]
    paths: [
      '.github/workflows/models-check.yml',
      'ggml/**',
      'tests/fusion/**',
      'tests/test-fusion.cpp',
      'tests/test-llama-archs.cpp',
      'src/llama-graph.cpp',
      'src/llama-model*',
      'src/models/**'
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  # note: this is dud token to avoid rate limiting (https://github.com/ggml-org/llama.cpp/pull/25706#issuecomment-4979941302)
  HF_TOKEN: ${{ secrets.HF_TOKEN_CI }}
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  rocm:
    runs-on: [self-hosted, Linux, gfx908]
    container: "rocm/dev-ubuntu-24.04:7.2.4-complete"

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential jq cmake time python3 python3-venv python3-pip

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.24
        with:
          restore: false
          save: false

      - name: ccache-buckets-restore
        uses: ./.github/actions/ccache-buckets
        with:
          key: models-check-rocm
          folder: llama.cpp
          hf_bucket: ggml-org/cache

      - name: Build
        id: cmake_build
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLAMA_FATAL_WARNINGS=ON \
            -DLLAMA_OPENSSL=OFF \
            -DGGML_SCHED_NO_REALLOC=ON \
            -DCMAKE_HIP_COMPILER=$(hipconfig -l)/clang \
            -DGPU_TARGETS=gfx908 \
            -DGGML_HIP=ON
          time cmake --build build --config Release --target test-llama-archs -j$(nproc)
          time cmake --build build --config Release --target test-fusion -j$(nproc)

      - name: ccache-buckets-save
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: ./.github/actions/ccache-buckets
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_CACHE_OUTPUT }}
        with:
          key: models-check-rocm
          folder: llama.cpp
          evict-old-files: 1d
          hf_bucket: ggml-org/cache
          save: true

      # - name: Generate models
      #   id: generate_models
      #   run: |
      #     rm -rf build-ci-models && mkdir -p build-ci-models
      #     ./build/bin/test-llama-archs -o build-ci-models

      # TODO: add for backends as they adopt the fusion debug API
      # - name: Test fusion
      #   id: test_fusion
      #   run: |
      #     ./build/bin/test-fusion --models build-ci-models --device CUDA0 --check tests/fusion/CUDA.csv

      - name: Test archs
        id: test_archs
        run: |
          GGML_CUDA_DEVICES=1 ./build/bin/test-llama-archs -s 1
          GGML_CUDA_DEVICES=2 ./build/bin/test-llama-archs -s 1
          GGML_CUDA_DEVICES=3 ./build/bin/test-llama-archs -s 1
          GGML_CUDA_DEVICES=4 ./build/bin/test-llama-archs -s 1
